server.port: 8090

spring:
  application:
    name: gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

eureka:
  instance:
    appname: gateway-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
